### ISSUE TITLE
Can't get the correct detailed mesh and image

### ISSUE THREAD

**Issue by QingXIA233** [YadiraF/DECA#83]
Hi, your work is really impressive! However, after I set everything properly and run the demo_reconstruct.py, I couldn't get the detailed mesh like what the README shows. I see other results like:
![example1](https://user-images.githubusercontent.com/64100948/140277341-f7bc9406-0683-48aa-ac3d-d10c87c2a82b.png)

But what I got is like:
![16_vis_original_size](https://user-images.githubusercontent.com/64100948/140277430-b64789e0-d508-4896-9fef-9cfbf9d34c71.jpg)

Everything is all right with the code, I tried both standard rasterization  and pytorch3d rasterization, I also tried useTex(I got the required texture npz file) and without using it, but in each case, I got the same results like I show above. Does anyone know the reason here and maybe give me some hint to get the correct results? Thank you all, maybe this is a stupid question but it really is driving me crazy.  :(

**Comment by Open-Debin** [comment]
Hello, I am also learn deca too. If you want to have a communication you can email me. michaeldbmeng19@outlook.com

**Comment by Natyen189** [comment]
This is exactly my issue right now too. Cant find what im missing tho

**Comment by cnpgs** [comment]
Are you referring to the texture shown in the [GIF](https://github.com/YadiraF/DECA/blob/master/Doc/images/soubhik.gif)? If so, I too have a similar issue. 

I can get the .obj and .mtl files that can be opened with MeshLab, but the texture is only visible for the non-detailed shape (.obj) file; in other words, the .obj file with name '<file_name>_detail.obj' only has the shape visible, and no texture. Also, the texture is nowhere near as complete as that shown in GIF:

![snapshot00](https://user-images.githubusercontent.com/22747334/144280041-d93e1164-c3d0-4826-84ad-d16f008c28aa.png)

**Comment by birdflies** [comment]
@cnpgs  I too have a similar issue. do you solve it?

**Comment by cnpgs** [comment]
> @cnpgs I too have a similar issue. do you solve it?

@birdflies No, unfortunately I have not solved it yet.

**Comment by qiliux** [comment]
I want to get the answer too..

**Comment by YadiraF** [comment]
Hi,

Thanks for pointing out this, it was a small bug in https://github.com/YadiraF/DECA/blob/f84855abf9f6956fb79f3588258621b363fa282c/decalib/deca.py#L304, 
I forgot to add color before. 
Just fixed this,  should work now, thanks!

**Comment by seawater668** [comment]
@yfeng95 Tried the latest code, still did not solve the problem mentioned above

**Comment by yaozhuyu-nreal** [comment]
> @yfeng95 Tried the latest code, still did not solve the problem mentioned above
https://github.com/yfeng95/DECA/blob/master/decalib/deca.py#L309, replacing dense_colors with dense_colors/255 will work.
